spring:
  application:
    name: SpringCloudConfig
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/smilejt/SpringCloudConfigFile.git
          search-paths: respo
          username: abandon_jt@163.com
          password: 2018newlife.
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/