#spring:
#  cloud:
#    config:
#      uri: http://localhost:8888
#      name: web-admin-feign
#      label: master
#      profile: dev
#      #dev：表示开发环境
#      #test：表示测试环境
#      #prod：表示生产环境

spring:
  application:
    name: SpringCloudWebAdminFeign
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
  boot:
    admin:
      client:
        url: http://localhost:8084
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8765

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

feign:
  hystrix:
    enabled: true