spring:
  application:
    name: SpringCloudEureka
  zipkin:
    base-url: http://abandon-jt.com:9411

server:
  port: 8761

eureka:
  instance:
    hostname: abandon-jt.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/