#spring:
#  cloud:
#    config:
#      uri: http://abandon-jt.com:8888
#      name: zuul
#      label: master
#      profile: dev

spring:
  application:
    name: SpringCloudZuul
  boot:
    admin:
      client:
        url: http://localhost:8084
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8769

eureka:
  client:
    serviceUrl:
      defaultZone: http://abandon-jt.com:8761/eureka/

zuul:
  routes:
    api-V1:
      path: /api/V1/**
      serviceId: SpringCloudWebAdminFeign