#spring:
##  cloud:
##    config:
##      uri: http://abandon-jt.com:8888
##      name: admin-server
##      label: master
##      profile: dev


spring:
  application:
    name: SpringCloudAdminServer
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8084

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info

eureka:
  client:
    serviceUrl:
      defaultZone: http://abandon-jt.com:8761/eureka/