#spring:
#  cloud:
#    config:
#      uri: http://localhost:8888
#      name: service-admin
#      label: master
#      profile: dev

spring:
  application:
    name: SpringCloudServiceAdmin
  boot:
    admin:
      client:
        url: http://localhost:8084
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8763

eureka:
  client:
    serviceUrl:
      defaultZone: http://abandon-jt.com:8761/eureka/